apiVersion: captain.benthos.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: benthos-captain
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: benthos-captain
  name: pipeline-sample
spec:
  replicas: 1
  config:
    input:
      generate:
        mapping: |
          let favorite_animal = env("FAVORITE_ANIMAL") 
          root = match $favorite_animal {
            "cat" => file("/config/cat.txt")
            "dog" => file("/config/dog.txt")
            _ => file("/config/dog.txt")
          }
        interval: 5s
        count: 0

    pipeline:
      processors:
        - mapping: root = content().uppercase()

    output:
      stdout: {}

  configFiles:
    cat.txt: |
      meow
    dog.txt: |
      woof

  env:
    - name: FAVORITE_ANIMAL
      value: cat
